### ISSUE TITLE
Comedy Central no longer able to play Full Episodes

### ISSUE THREAD

**Issue by shopgirl284** [plexinc-plugins/Services.bundle#938]
The Comedy Central URL service fails to play Full Episodes. The website has changed the code of the players for full episodes. Clips still work.

It returns a media unavailable error on line 94, because it can no longer find the mgid, which is no longer listed in the web page source code for full episodes. They seem to be using json for the player now and just list an ID number.

**Comment by sander1** [comment]
I think I found a way to update this and do it for both clips and full episodes.

**Comment by sander1** [comment]
Fixed with https://github.com/plexinc-plugins/Services.bundle/commit/82d27e57888f5d553b23e56d319bdc641df4601f Update will be pushed out later today.

**Comment by 23rdstreet** [comment]
For some reason, its still giving me a "this channel is not responding" error...  I've reset & restarted the channel under the update option.

**Comment by gbcox** [comment]
I'm still having an issue also.  I even deleted and re-installed the channel... still not working

**Comment by kingblakeAL** [comment]
Yeah, still not working. Server, all channels and apps up to date.

**Comment by gbcox** [comment]
See issue #939 - it's working now.  You may need to delete the channel and reinstall.

**Comment by michaelh99** [comment]
I've uninstalled and reinstalled the channel and it's still not working for me.  Does this update require the 1.2.7 server?

**Comment by gbcox** [comment]
I'm running the DVR Beta 3 version and it's working for me:  
plexmediaserver-1.2.0.2838-a68e2fe.x86_64

**Comment by michaelh99** [comment]
Ok, I've found a workaround even after installing the latest version
I have to drill down through Comedy Central -> Shows -> All Shows -> D -> Daily Show (Noah) and I'm able to watch episodes.
If I go through the menus I've been using for the last year of Comedy Central ->Full Episodes -> Daily Show (Noah) I just get "this channel is not responding"

**Comment by 23rdstreet** [comment]
Hey Guys, this is what worked for me: manually discard the "comedy central.bundle" file in "~Library/Application Support/Plex Media Server/Plug-ins/" & reinstall the channel via the web interface.

**Comment by gbcox** [comment]
@michaelh99 I'm able to select:  Full Episodes, then click on the Daily Show, and then select the episode.  Works fine for me.

**Comment by michaelh99** [comment]
I used @23rdstreet's method by manually removing the bundle.  That worked.  Apparently removing the channel through the web interface doesn't remove everything.

**Comment by kingblakeAL** [comment]
It does not work for me.

**Comment by WafflesMcDuff** [comment]
It still does not work for me. I tried deleting C:\Users\<username>\AppData\Local\Plex Media Server\Plug-ins\Comedy Central.bundle and reinstalling the plugin, but that didn't help

**Comment by sander1** [comment]
Make sure you have at least Plex Media Server version 1+

Lots of updates are done in _Services.bundle_. If this budle got corrupted somehow, try if deleting it works:
1. Quit Plex Media Server
2. Find the plugins folder (https://support.plex.tv/hc/en-us/articles/201106098-How-do-I-find-the-Plug-Ins-folder-)
3. Delete Services.bundle
4. Restart Plex Media Server and give it a few minutes to download a fresh copy if the Services bundle

**Comment by locomot1f** [comment]
nope still not getting it.
i've tried everything listed above.
doing a fresh install, ATM

**Comment by locomot1f** [comment]
i can't even get clips to work... argh!!!

**Comment by michaelh99** [comment]
There are semi-regular periods where CC just doesn't work for some shows.  Things usually start working again a day or two later.
It looks like we're in another period of it not working.  I haven't made any changes and it's not working for me either.

**Comment by locomot1f** [comment]
thanks for the reply!!!
let me know i'm not completely gone insane!

**Comment by michaelh99** [comment]
Honestly the only reason I *have* plex is to watch CC.  Guess it's time to cancel my subscription to Plex, too.

**Comment by locomot1f** [comment]
they are notorious for changing their website... seems like every month.

**Comment by sander1** [comment]
We're aware of the new issues and looking into a solution.

**Comment by sander1** [comment]
> Honestly the only reason I have plex is to watch CC. Guess it's time to cancel my subscription to Plex, too.

Channels are maintained by volunteers from the community, they're free and available without any subscription. Channels are unofficial, we don't work with or have contact with the content providers, so if they change anything, the channel will break and someone with some time on their hands has to jump in and create a fix. That can also take a bit of time.

**Comment by michaelh99** [comment]
@sander1 thanks for the info.  Do you know of any back-room discussions to make any/all channels full plex citizens?

**Comment by gbcox** [comment]
This also affects the "South Park" channel.

**Comment by Asghardhyl** [comment]
Hello guys, i've just installed the Channel but it doesn't work.
I did some modifications as recommended : delete Services.bundle or Comedy Central.bundle but it didn't help...
Any news on your side ? Can't watch Full episodes.

**Comment by michaelh99** [comment]
Yeah, CC probably changed something again.  Not working for me either.

I wish Plex would just drop CC support since they can't make it a first-class citizen due to lack of support from CC.
Every night it's  a game of "can I watch CC tonight? ..."

**Comment by gbcox** [comment]
@michaelh99 speak for yourself.  If you're not satisfied with the plugin, don't use it.  There are many people who enjoy it when it is functioning.

**Comment by michaelh99** [comment]
@gbcox  I very clearly *was* speaking for myself.  I also very clearly wasn't complaining about the plugin but the lack of support from CC

**Comment by Asghardhyl** [comment]
Bah nevermind, just hope that CC will work soon enough :)

**Comment by gbcox** [comment]
@michaelh99 Viacom doesn't work for Plex and could care less about the Plex plugin.  Wishing the plugin would be dropped doesn't affect just you... so if you're not happy with it you don't want anybody to be able to use it?  Viacom provides officially supported methods to access their content.  This isn't one of them.
